server {
    listen  81 ssl;

    ssl_certificate /cert/nginx-selfsigned.crt;
    ssl_certificate_key /cert/nginx-selfsigned.key;

    location / {
        proxy_pass  http://service1:80;
    }
}
server {
    listen  82 ssl;

    ssl_certificate /cert/nginx-selfsigned.crt;
    ssl_certificate_key /cert/nginx-selfsigned.key;

    location / {
        proxy_pass  http://service2:80;
    }
}